/**
 * Generated file by convert_csv script.
 */

export const Questions = [
  ['incorporates constructive feedback', 'Seek to improve', 1],
  ['is open to feedback', 'Seek to improve', 1],
  ['knows their own weaknesses', 'Seek to improve', 1],
  ["openly admits they don't know something", 'Seek to improve', 1],
  ['self-drives their development', 'Seek to improve', 1],
  ['gives useful feedback to me', 'Seek to improve', 1],
  ['regularly shares knowledge', 'Seek to improve', 1],
  ['appears to meetings on time', 'Teamwork', 1],
  ['is empathetic', 'Teamwork', 1],
  ["values other people's opinions", 'Teamwork', 1],
  ['offers help to others', 'Teamwork', 1],
  ['spends time to answer questions', 'Teamwork', 1],
  ['is a good mentor', 'Teamwork', 1],
  ['treats others with respect', 'Teamwork', 1],
  ['actively participates in group meetings', 'Teamwork', 1],
  ['apologizes for failures', 'Teamwork', 1],
  ['is friendly', 'Teamwork', 1],
  ["respects other people's opinions", 'Teamwork', 1],
  ['is fair', 'Teamwork', 1],
  ['is judgemental', 'Teamwork', 0],
  ['is open-minded', 'Teamwork', 1],
  ['is good at negotiations', 'Teamwork', 1],
  ['is good at coaching others', 'Teamwork', 1],
  ['expects others to take the lead', 'Teamwork', 0],
  ['can lead a discussion', 'Teamwork', 1],
  ['is a good listener', 'Teamwork', 1],
  ['is passive', 'Teamwork', 0],
  ['regularly supports me in my work', 'Teamwork', 1],
  ['rushes decisions', 'Delivery', 0],
  ['avoids decisions', 'Delivery', 0],
  ['takes responsibility for their actions', 'Delivery', 1],
  ['does reviews on time', 'Delivery', 1],
  ['is passionate about their work', 'Delivery', 1],
  ['can manage stress', 'Delivery', 1],
  ['keeps commitments', 'Delivery', 1],
  ['proactively uses feature flags', 'Delivery', 1],
  ['supports finishing team commitment of our sprints', 'Delivery', 1],
  ['delivered a feature that had a lot of uncertainty', 'Delivery', 1],
  ['shares their opinion actively', 'Communication', 1],
  ['is the voice of reason', 'Communication', 1],
  ['communicates well', 'Communication', 1],
  ['communicates their actions well', 'Communication', 1],
  ['speaks in understandable terms', 'Communication', 1],
  ['gives clear status updates in the daily', 'Communication', 1],
  ['clarifies questions early on', 'Communication', 1],
  ['communicates complex ideas skillfully', 'Communication', 1],
  ['takes ownership of their products', 'Ownership', 1],
  ['finishes their tasks before the end of the sprint', 'Ownership', 1],
  ['Helps improving our monitoring', 'Ownership', 1],
  ['is a great firefighter', 'Ownership', 1],
  ['acts responsibly', 'Strategic Thinking', 1],
  ['executes requirements accurately', 'Strategic Thinking', 1],
  [
    "brings the customer's perspective into discussions",
    'Strategic Thinking',
    1,
  ],
  [
    'Asks for details to understand the impact during refinement',
    'Strategic Thinking',
    1,
  ],
  ['involved in the definition of the team strategy', 'Strategic Thinking', 1],
  ['advocates for the technical strategy', 'Strategic Thinking', 1],
  ['understands our team goals', 'Strategic Thinking', 1],
  ['acts according to our companies priorities', 'Strategic Thinking', 1],
  ['exhibits leadership qualities in their position', 'Mastery', 1],
  ['gives a professional impression', 'Mastery', 1],
  ['delivers high quality work', 'Mastery', 1],
  ['is pragmatic', 'Mastery', 1],
  ['does careful reviews', 'Mastery', 1],
  ['has a professional attitude', 'Mastery', 1],
  ['is a role model', 'Mastery', 1],
  ['can execute their tasks independently', 'Mastery', 1],
  ['cares about quality', 'Mastery', 1],
  ['is someone I can learn from', 'Mastery', 1],
  ['is knowledgable', 'Mastery', 1],
  ['works effectively', 'Mastery', 1],
  ['is enjoyable to work with', 'Mastery', 1],
  ['actively seeks solutions', 'Mastery', 1],
  ['takes unnecessary risks', 'Mastery', 0],
  ['assesses risks before taking actions', 'Mastery', 1],
  ['has endurance for the long haul', 'Mastery', 1],
  ['can communicate a clear vision', 'Mastery', 1],
  ['thinks in long term solutions instead of quick fixes', 'Mastery', 1],
  ['pays attention to detail', 'Mastery', 1],
  ['finds innovative solutions to problems', 'Mastery', 1],
  ['is good at researching problems', 'Mastery', 1],
  ['is good at troubleshooting', 'Mastery', 1],
  ['is focused', 'Mastery', 1],
];
